try {
    evaaal();
} catch (err) {
    throw new EvalError('Se ha producido un error','ejercicio13.js', 100);
}