try{
    console("Hola")
} catch(e){ 
    throw new EvalError('Se ha producido un error, ejercicio13.js, en el bloque try');
}

