try {
    throw new RangeError(['Se ha producido un error',['ejercicio13.js', [100]]]);
} catch (error) {
    throw new RangeError(['Se ha producido un error', ['ejercicio13.js', [100]]]);
}