try {
    throw new EvalError("Se ha prodicido un error, ejercicio13.js " + 100)
} catch (error) {
    throw new EvalError("Se ha prodicido un error, ejercicio13.js " + 100)
}